### PR TITLE
Sending the morning briefing event

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by tomrf1** [comment]
👍 after test

**Comment by shtukas** [comment]
Test1
```
START RequestId: d40bc46e-f9d5-11e6-9a53-ebddb3f4e840 Version: $LATEST
AwardEvent(Best Actor,Andrew Garfield in Hacksaw Ridge) is valid
{"userId":"1371010886265568","isMorningBriefing":false,"data":{"category":"Best Actor","winner":"Andrew Garfield in Hacksaw Ridge","userPrediction":"Casey Affleck in Manchester by the Sea","percentageWhoAgreedWithNom":0.5}}
{"userId":"1238481182885832","isMorningBriefing":false,"data":{"category":"Best Actor","winner":"Andrew Garfield in Hacksaw Ridge","userPrediction":"Denzel Washington in Fences","percentageWhoAgreedWithNom":0.5}}
END RequestId: d40bc46e-f9d5-11e6-9a53-ebddb3f4e840
REPORT RequestId: d40bc46e-f9d5-11e6-9a53-ebddb3f4e840	Duration: 22967.62 ms	Billed Duration: 23000 ms 	Memory Size: 256 MB	Max Memory Used: 108 MB	
```

**Comment by shtukas** [comment]
Test2
```
START RequestId: 39681a9c-f9d6-11e6-b247-2d6b716f01de Version: $LATEST
AwardEvent(Best Actor,Andrew Garfield in Hacksaw Ridge) is valid
{"userId":"1371010886265568","isMorningBriefing":false,"data":{"category":"Best Actor","winner":"Andrew Garfield in Hacksaw Ridge","userPrediction":"Casey Affleck in Manchester by the Sea","percentageWhoAgreedWithNom":0.5}}
{"userId":"1238481182885832","isMorningBriefing":false,"data":{"category":"Best Actor","winner":"Andrew Garfield in Hacksaw Ridge","userPrediction":"Denzel Washington in Fences","percentageWhoAgreedWithNom":0.5}}
END RequestId: 39681a9c-f9d6-11e6-b247-2d6b716f01de
REPORT RequestId: 39681a9c-f9d6-11e6-b247-2d6b716f01de	Duration: 2335.16 ms	Billed Duration: 2400 ms 	Memory Size: 256 MB	Max Memory Used: 102 MB
```

**Comment by shtukas** [comment]
@tomrf1 Tested! Merging.

**Pull request merged**
