### PR TITLE
Adding scanamo dependency

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by LATaylor-guardian** [comment]
This doesn't need to be a PR on it's own 😆 but 👍

**Comment by shtukas** [comment]
I am making small ones to make them easier to review :)

**Comment by LATaylor-guardian** [comment]
They don't need to be this small, the overhead of creating a PR and waiting for a 👍  and deploying the change is greater than the time taken to make the actual change 😄

**Comment by shtukas** [comment]
You are right :)
I am just trying to find the sweet spot :)

**Pull request merged**
