### PR TITLE
Change in rolling updates message format

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by shtukas** [comment]
Tested!
```
START RequestId: aa2b30fa-f8f2-11e6-9cde-2198e6221642 Version: $LATEST
AwardEvent(Best Actor,Andrew Garfield in Hacksaw Ridge) is valid
[{"userId":"1371010886265568","category":"Best Actor","winner":"Andrew Garfield in Hacksaw Ridge","userPrediction":"Casey Affleck in Manchester by the Sea","percentageWhoAgreedWithNom":0.5}]
[{"userId":"1238481182885832","category":"Best Actor","winner":"Andrew Garfield in Hacksaw Ridge","userPrediction":"Denzel Washington in Fences","percentageWhoAgreedWithNom":0.5}]
END RequestId: aa2b30fa-f8f2-11e6-9cde-2198e6221642
REPORT RequestId: aa2b30fa-f8f2-11e6-9cde-2198e6221642	Duration: 2381.64 ms	Billed Duration: 2400 ms 	Memory Size: 256 MB	Max Memory Used: 104 MB	
```

**Comment by tomrf1** [comment]
I think the only functional change here is that it now sends a List, is that right?
`handleRequest` appears to be the same, just moved.

**Comment by annebyrne** [comment]
:+1: LGTM!

**Comment by shtukas** [comment]
@tomrf1 That's right!

**Comment by shtukas** [comment]
Merging now!

**Comment by tomrf1** [comment]
👍

**Pull request merged**
